name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Adjust this if you use a different branch for deployments

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .  # Path to Dockerfile
          file: ./backend/Dockerfile  # Path to your backend Dockerfile
          push: true
          tags: sahilbhalekar/courses-api-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .  # Path to Dockerfile
          file: ./frontend/Dockerfile  # Path to your frontend Dockerfile
          push: true
          tags: sahilbhalekar/courses-api-frontend:latest

      - name: Postgres image build (optional)
        run: |
          echo "Postgres is using the official image and doesn't need building."
